-- Schéma PostgreSQL pour l'annuaire des formations (Sprint 4)

create type annee_statut as enum ('EN_COURS', 'PREPARATION', 'ARCHIVEE');
create type entite_type as enum ('COMPOSANTE', 'DEPARTEMENT', 'MENTION', 'PARCOURS', 'NIVEAU');
create type utilisateur_statut as enum ('ACTIF', 'INACTIF');
create type utilisateur_genre as enum ('M', 'F');
create type utilisateur_categorie as enum ('EC', 'BIATSS', 'ESAS', 'CONTRACTUEL', 'VACATAIRE');
create type composante_type as enum ('UFR', 'INSTITUT', 'IUT');
create type personne_externe_statut as enum ('ANCIEN_ETUDIANT', 'PROFESSIONNEL');
create type demande_statut as enum ('EN_ATTENTE', 'VALIDEE', 'REFUSEE');
create type delegation_statut as enum ('ACTIVE', 'EXPIREE', 'ANNULEE');
create type signalement_statut as enum ('OUVERT', 'EN_COURS', 'CLOTURE');

create table annee_universitaire (
  id_annee bigint generated by default as identity primary key,
  libelle text not null,
  date_debut date not null,
  date_fin date not null,
  statut annee_statut not null,
  id_annee_source bigint references annee_universitaire(id_annee),
  constraint annee_dates_chk check (date_debut <= date_fin)
);

create table entite_structure (
  id_entite bigint generated by default as identity primary key,
  id_annee bigint not null references annee_universitaire(id_annee),
  id_entite_parent bigint references entite_structure(id_entite),
  type_entite entite_type not null,
  nom text not null,
  tel_service text,
  bureau_service text,
  constraint entite_parent_chk check (id_entite_parent is null or id_entite_parent <> id_entite)
);

create table composante (
  id_entite          bigint primary key references entite_structure(id_entite) on delete cascade,
  code_composante    text,
  type_composante    composante_type,
  site_web           text,
  mail_fonctionnel   text,
  mail_institutionnel text,
  campus             text
);

create table departement (
  id_entite bigint primary key references entite_structure(id_entite) on delete cascade,
  code_interne text
);

-- Table de référence des types de diplômes (39 types identifiés — Sprint 4 §9)
create table type_diplome (
  id_type_diplome bigint generated by default as identity primary key,
  libelle text not null unique,
  is_active boolean not null default true
);

create table mention (
  id_entite       bigint primary key references entite_structure(id_entite) on delete cascade,
  type_diplome    text,
  cycle           int,
  id_type_diplome bigint references type_diplome(id_type_diplome) on delete set null
);

create table parcours (
  id_entite bigint primary key references entite_structure(id_entite) on delete cascade,
  code_parcours text
);

create table niveau (
  id_entite bigint primary key references entite_structure(id_entite) on delete cascade,
  libelle_court text
);

create table utilisateur (
  id_user          bigint generated by default as identity primary key,
  login            text not null unique,
  uid_cas          text,
  nom              text not null,
  prenom           text not null,
  genre            utilisateur_genre,
  categorie        utilisateur_categorie,
  email_institutionnel text,
  email_institutionnel_secondaire text,
  telephone        text,
  bureau           text,
  statut           utilisateur_statut not null default 'ACTIF'
);

-- Personnalités extérieures sans CAS (Sprint 4 §27)
create table personne_externe (
  id_externe     bigint generated by default as identity primary key,
  nom            text not null,
  prenom         text not null,
  entreprise     text,
  statut_externe personne_externe_statut,
  email          text
);

create table role (
  id_role             text primary key,
  libelle             text not null,
  description         text,
  niveau_hierarchique int not null default 0,
  is_global           boolean not null default true,
  est_administratif   boolean not null default false,
  est_transverse      boolean not null default false,
  id_composante       bigint references entite_structure(id_entite) on delete set null
);

create table affectation (
  id_affectation          bigint generated by default as identity primary key,
  id_user                 bigint not null references utilisateur(id_user),
  id_role                 text not null references role(id_role),
  id_entite               bigint not null references entite_structure(id_entite),
  id_annee                bigint not null references annee_universitaire(id_annee),
  date_debut              date not null,
  date_fin                date,
  id_affectation_n_plus_1 bigint references affectation(id_affectation) on delete set null,
  constraint affectation_unique unique (id_user, id_role, id_entite, id_annee)
);

create table contact_role (
  id_contact_role     bigint generated by default as identity primary key,
  id_affectation      bigint not null references affectation(id_affectation) on delete cascade,
  email_fonctionnelle text,
  type_email          text,
  telephone           text,
  bureau              text
);

create table demande_role (
  id_demande_role    bigint generated by default as identity primary key,
  id_user_createur   bigint not null references utilisateur(id_user),
  id_user_validateur bigint references utilisateur(id_user) on delete set null,
  role_propose       text not null,
  description        text,
  justificatif       text,
  statut             demande_statut not null default 'EN_ATTENTE',
  date_creation      timestamptz not null default now(),
  date_decision      timestamptz
);

create table delegation (
  id_delegation   bigint generated by default as identity primary key,
  delegant_id     bigint not null references utilisateur(id_user),
  delegataire_id  bigint not null references utilisateur(id_user),
  id_entite       bigint not null references entite_structure(id_entite),
  id_role         text references role(id_role),
  type_droit      text,
  date_debut      date not null,
  date_fin        date,
  statut          delegation_statut not null default 'ACTIVE'
);

create table journal_audit (
  id_log          bigint generated by default as identity primary key,
  id_user_auteur  bigint not null references utilisateur(id_user),
  horodatage      timestamptz not null default now(),
  type_action     text not null,
  cible_type      text not null,
  cible_id        text,
  ancienne_valeur text,
  nouvelle_valeur text
);

create table demande_modification (
  id_demande      bigint generated by default as identity primary key,
  auteur_id       bigint not null references utilisateur(id_user),
  validateur_id   bigint references utilisateur(id_user) on delete set null,
  cible_type      text not null,
  cible_id        text not null,
  champ           text not null,
  valeur_proposee text,
  statut          demande_statut not null default 'EN_ATTENTE',
  date_creation   timestamptz not null default now(),
  date_decision   timestamptz
);

create table signalement (
  id_signalement              bigint generated by default as identity primary key,
  auteur_id                   bigint not null references utilisateur(id_user),
  traitant_id                 bigint references utilisateur(id_user) on delete set null,
  cloture_par_id              bigint references utilisateur(id_user) on delete set null,
  id_entite_cible             bigint references entite_structure(id_entite) on delete set null,
  description                 text not null,
  statut                      signalement_statut not null default 'OUVERT',
  date_creation               timestamptz not null default now(),
  date_prise_en_charge        timestamptz,
  date_traitement             timestamptz,
  commentaire_prise_en_charge text,
  commentaire_cloture         text
);

create table notification (
  id_notif        bigint generated by default as identity primary key,
  destinataire_id bigint not null references utilisateur(id_user),
  message         text not null,
  date_envoi      timestamptz not null default now(),
  lu              boolean not null default false,
  id_demande      bigint references demande_modification(id_demande) on delete set null,
  id_signalement  bigint references signalement(id_signalement) on delete set null,
  id_demande_role bigint references demande_role(id_demande_role) on delete set null
);

create table organigramme (
  id_organigramme  bigint generated by default as identity primary key,
  id_annee         bigint not null references annee_universitaire(id_annee),
  id_entite_racine bigint not null references entite_structure(id_entite),
  generated_by     bigint not null references utilisateur(id_user),
  generated_at     timestamptz not null default now(),
  est_fige         boolean not null default false,
  export_path      text,
  export_format    text not null default 'PDF',
  visibility_scope text
);

-- ─── Index ───────────────────────────────────────────────────────────────────
create index idx_entite_annee        on entite_structure(id_annee);
create index idx_entite_parent       on entite_structure(id_entite_parent);
create index idx_mention_type_diplome on mention(id_type_diplome);
create index idx_affectation_annee   on affectation(id_annee);
create index idx_affectation_entite  on affectation(id_entite);
create index idx_affectation_role    on affectation(id_role);
create index idx_affectation_user    on affectation(id_user);
create index idx_affectation_n_plus_1 on affectation(id_affectation_n_plus_1);
create index idx_contact_role_affectation on contact_role(id_affectation);
create index idx_delegation_delegant    on delegation(delegant_id);
create index idx_delegation_delegataire on delegation(delegataire_id);
create index idx_delegation_entite      on delegation(id_entite);
create index idx_role_composante        on role(id_composante);
create index idx_audit_auteur           on journal_audit(id_user_auteur);
create index idx_demande_modif_auteur       on demande_modification(auteur_id);
create index idx_demande_modif_validateur   on demande_modification(validateur_id);
create index idx_demande_role_createur      on demande_role(id_user_createur);
create index idx_demande_role_validateur    on demande_role(id_user_validateur);
create index idx_signalement_auteur         on signalement(auteur_id);
create index idx_signalement_entite         on signalement(id_entite_cible);
create index idx_signalement_traitant       on signalement(traitant_id);
create index idx_notification_demande       on notification(id_demande);
create index idx_notification_demande_role  on notification(id_demande_role);
create index idx_notification_destinataire  on notification(destinataire_id);
create index idx_notification_signalement   on notification(id_signalement);
create index idx_organigramme_annee         on organigramme(id_annee);
create index idx_organigramme_entite        on organigramme(id_entite_racine);
create index idx_organigramme_generated_by  on organigramme(generated_by);
